[project]
name = "comp6577001"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gensim>=4.3.3",
    "pandas>=2.2.3",
    "pip>=25.0.1",
    "scikit-learn>=1.6.1",
    "spacy>=3.8.4",
]

[tool.uv.workspace]
members = [ "furry-and-weeb-terms-analyzer/", "subculture-post-classifier/" , "dataset-filter"]

[dependency-groups]
dev = [
    "ruff>=0.9.7",
]
